### PR TITLE
Created api controller returning sample data

### PR DESCRIPTION
**Pull request by ozarychta**
GetByOrderId is ready, Post method (it's called Post, because i forgot to name that method, that should be something like GetByDateTimeAndContent  xd) and that will be refactored, very likely changed, possibly splited into few smaller methods.

### CODE REVIEW

**Comment by pdomagala** [comment]
Looks good to me, @OskarPrzybylski do you agree with me?

**Comment by OskarPrzybylski** [comment]
@ozarychta Just refactor name of the method "Post" please and it will be good then.

**Comment by ozarychta** [comment]
I refactored what you told me to and slightly changed structure of api requests and responses (README.md is already updated so you can take a look).

**Review by pdomagala — APPROVED** [review]

**Comment by pdomagala** [comment]
Looks fine, but remember to update CHANGELOG.md in next pull requests

**Pull request merged**
